; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{A50FAE81-4A31-4BEB-90FE-634963797820}
AppName=speechandattaack
AppVersion=1.3.1
;AppVerName=speechandattaack 1.3.1
AppPublisher=Danh Thành, Inc.
AppPublisherURL=http://www.example.com/
AppSupportURL=http://www.example.com/
AppUpdatesURL=http://www.example.com/
DefaultDirName={pf}\speechandattaack
DefaultGroupName=speechandattaack
AllowNoIcons=yes
OutputDir=C:\Users\admin\Desktop
OutputBaseFilename=setup
Password=123456
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "finnish"; MessagesFile: "compiler:Languages\Finnish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 0,6.1

[Files]
Source: "C:\Users\admin\Desktop\import\Python\S&A-Speak and attack\source.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\admin\Desktop\import\Python\S&A-Speak and attack\source.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\admin\Desktop\import\Python\S&A-Speak and attack\display.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\admin\Desktop\import\Python\S&A-Speak and attack\__pycache__\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\admin\Desktop\import\Python\S&A-Speak and attack\audio\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\admin\Desktop\import\Python\S&A-Speak and attack\data\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\admin\Desktop\import\Python\S&A-Speak and attack\image\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\speechandattaack"; Filename: "{app}\source.exe"
Name: "{group}\{cm:ProgramOnTheWeb,speechandattaack}"; Filename: "http://www.example.com/"
Name: "{group}\{cm:UninstallProgram,speechandattaack}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\speechandattaack"; Filename: "{app}\source.exe"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\speechandattaack"; Filename: "{app}\source.exe"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\source.exe"; Description: "{cm:LaunchProgram,speechandattaack}"; Flags: nowait postinstall skipifsilent

